export default {
  'request.error': 'Request failed',
  // nav
  'nav.dashboard': 'Dashboard',
  'nav.subscribe': 'Subscription',
  'nav.my_subscribe': 'My Subscriptions',
  'nav.buy_subscribe': 'Purchase Subscription',
  'nav.bill': 'Billing',
  'nav.my_order': 'My Orders',
  'nav.my_invite': 'My Invitation',
  'nav.user': 'Account',
  'nav.user_center': 'Profile',
  'nav.my_ticket': 'My Tickets',
  'nav.traffic_detail': 'Transfer Data Details',
  'nav.tutorial': 'Tutorial',
  // dashboard
  'dashboard.not_bind_telegram': 'No link to Telegram yet',
  'dashboard.click_here_bind': 'Please click here to link to Telegram',
  'dashboard.announcement': 'Announcements',
  'dashboard.override': 'Overview',
  'dashboard.pending_order': 'Pending Orders',
  'dashboard.pending_ticket': 'Pending Tickets',
  'dashboard.my_invite': 'My Invitation',
  'dashboard.my_subscribe': 'My Subscription',
  'dashboard.add_subscribe': 'Order a subscription',
  'dashboard.not_expire': 'The subscription is valid for unlimited time',
  'dashboard.expired': 'Expired',
  'dashboard.subscribe_info': 'Will expire on {date}, {Day} days before expiration, after {reset_day} days reset transfer data',
  'dashboard.traffic_info': '{used} Used / Total {total}',
  'dashboard.view_subscribe': 'View Subscription',
  'dashboard.renew': 'Renew',
  // forgetPassword
  'forgetPassword.email': 'Email',
  'forgetPassword.email_verify_code': 'Email verification code',
  'forgetPassword.send': 'Send',
  'forgetPassword.password': 'Password',
  'forgetPassword.reset_password': 'Reset password',
  'forgetPassword.back_login': 'Back to login',
  // invite
  'invite.table_code': 'Invitation Code',
  'invite.table_create_time': 'Creation Time',
  'invite.table_action': 'Action',
  'invite.copy_link': 'Copy link',
  'invite.table_complete_time': 'Complete Time',
  'invite.table_commission_balance': 'Commission',
  'invite.table_commission_status': 'Commission Status',
  'invite.override': 'Invitation overview',
  'invite.register_count': 'Number of registered users',
  'invite.commission_rate': 'Commission rate',
  'invite.confirm_commission': 'Pending commission',
  'invite.confirm_commission_tip': 'The commission will reach your commission account after review.',
  'invite.invite_code_manage': 'Invitation Code Management',
  'invite.generate_code': 'Generate invitation code',
  'invite.detail': 'Invitation Details',
  'invite.copy_success': 'Copied successfully',
  // login
  'login.email': 'Email',
  'login.password': 'Password',
  'login': 'Login',
  'login.register': 'Register',
  'login.forget_password': 'Forgot password',
  // order
  'order.table_no': 'Order Number #',
  'order.table_cycle': 'Cycle',
  'order.table_amount': 'Order Amount',
  'order.table_status': 'Order Status',
  'order.table_create_time': 'Creation Time',
  'order.table_action': 'Action',
  'order.view_detail': 'View Details',
  'order.cancel': 'Cancel',
  'order.order_manage': 'Order Management',
  'order.please_select_pay_method': 'Please select a payment method',
  'order.please_check_credit_card': 'Please check credit card payment information',
  'order.order_detail': 'Order Details',
  'order.product': 'Product',
  'order.type_cycle': 'Type/Cycle',
  'order.amount': 'Amount',
  'order.traffic': 'Transfer Data',
  'order.discount': 'Discount',
  'order.surplus': 'Discounted',
  'order.refund': 'Refund',
  'order.balance_pay': 'Pay with balance',
  'order.pay_method': 'Payment Method',
  'order.enter_credit_info': 'Fill in credit card payment information',
  'order.credit_alert': 'We will not collect your credit card information, credit card number and other details only use to verify the current transaction.',
  'order.total_amount': 'Order Total',
  'order.total': 'Total',
  'order.checkout': 'Checkout',
  'order.waiting_payment': 'Waiting for payment',
  // plan
  'plan.select_subscribe': 'Select a subscription',
  'plan.buy': 'Subscribe now',
  'plan.setting_subscribe': 'Configure subscription',
  'plan.discount': 'Discount',
  'plan.cycle': 'Payment Cycle',
  'plan.have_coupon': 'Have coupons?',
  'plan.coupon_verify': 'Verify',
  'plan.order_total_amount': 'Order total',
  'plan.place_order': 'Order',
  'plan.total': 'Total',
  // profile
  'profile.user_center': 'User Center',
  'profile.my_wallet': 'My Wallet',
  'profile.balance_tip': 'Account Balance (For billing only)',
  'profile.commission_balance_tip': 'Invitation Commission (Can be used to withdraw)',
  'profile.wallet_component': 'Wallet Details',
  'profile.transfer': 'Transfer',
  'profile.commission_withdraw': 'Invitation commission withdrawal',
  'profile.change_password': 'Change password',
  'profile.save': 'Save',
  'profile.old_password': 'Old password',
  'profile.new_password': 'New password',
  'profile.re_new_password': 'New password',
  'profile.please_enter_old_password': 'Please enter the old password',
  'profile.please_enter_new_password': 'Please enter the new password',
  'profile.please_enter_re_new_password': 'Please enter the new password again',
  'profile.notice': 'Notice',
  'profile.expire_remind': 'Subscription expiration email reminder',
  'profile.traffic_remind': 'Insufficient transfer data email alert',
  'profile.bind_telegram': 'Link to Telegram',
  'profile.start': 'Start Now',
  'profile.reset_subscribe': 'Reset subscription',
  'profile.reset': 'Reset',
  'profile.reset_info_notify_title': 'Do you want to reset subscription?',
  'profile.reset_info_notify_content': 'In case of account information or your subscription leak this option is used to reset your UUID and subscription will be changed after reset, you need to re-subscribe.',
  'profile.reset_info_notify_success': 'Reset successfully',
  'profile.two_password_error': 'Two new passwords entered do not match',
  // reg
  'register.two_password_error': 'The passwords entered do not match',
  'register.email': 'Email',
  'register.verify_code': 'Email verification code',
  'register.password': 'Password',
  'register.re_password': 'Password',
  'register.send': 'Send',
  'register.invite_code_require': 'Invitation code',
  'register.invite_code': 'Invitation code (Optional)',
  'register': 'Register',
  'register.back_login': 'Back to login',
  // subscribe
  'subscribe.table_name': 'Name',
  'subscribe.table_tag': 'Tags',
  'subscribe.table_action': 'Action',
  'subscribe.table_status': 'Status',
  'subscribe.table_status_tip': 'Access point online status within 5 minutes',
  'subscribe.table_rate': 'Rate',
  'subscribe.table_rate_tip': 'The transfer data used is multiplied by the transfer data rate deducted',
  'subscribe.more_action': 'More actions',
  'subscribe.copy_success': 'Copied successfully',
  'subscribe.copy_link': 'Copy link',
  'subscribe.my_subscribe': 'My subscription',
  'subscribe.add_subscribe': 'Order a subscription',
  'subscribe.not_expire': 'The subscription is valid for unlimited time',
  'subscribe.expired': 'Expired',
  'subscribe.subscribe_info': 'Will expire on {date}, {Day} days before expiration, after {reset_day} days reset transfer data',
  'subscribe.traffic_info': '{used} Used / Total {total}',
  'subscribe.renew': 'Renew',
  'subscribe.action': 'Action',
  'subscribe.reset_traffic': 'Reset current month traffic',
  'subscribe.reset_info': 'Reset subscription',
  'subscribe.node_status': 'Access Point Status',
  'subscribe.no_node': 'No access points available, if you have not subscribed a subscription or the subscription has been expired, please',
  'subscribe.no_node_renew': 'Renew',
  'subscribe.no_node_go': 'Subscribe',
  'subscribe.reset_traffic_notify_title': 'Are you sure to reset the current month\'s transfer data?',
  'subscribe.reset_traffic_notify_content': 'Click "Confirm" and you will be redirected to the payment page. After the order is paid, the system will clear your used data for the month.',
  'subscribe.reset_traffic_notify_confirm': 'Confirm',
  'subscribe.reset_traffic_notify_cancel': 'Cancel',
  'subscribe.reset_info_notify_title': 'Are you sure to reset subscription?',
  'subscribe.reset_info_notify_content': 'In case of account information or your subscription leak this option is used to reset your UUID and subscription will be changed after reset, you need to re-subscribe.',
  'subscribe.reset_info_notify_success': 'Reset successfully',
  // ticket
  'ticket.low': 'Low',
  'ticket.middle': 'Medium',
  'ticket.high': 'High',
  'ticket.table_subject': 'Subject',
  'ticket.table_level': 'Ticket Priority',
  'ticket.table_status': 'Ticket Status',
  'ticket.table_create_time': 'Creation Time',
  'ticket.table_last_reply': 'Last Reply',
  'ticket.table_action': 'Action',
  'ticket.status_closed': 'Closed',
  'ticket.status_pending': 'Pending Reply',
  'ticket.status_reply': 'Replied',
  'ticket.action_view': 'View',
  'ticket.action_close': 'Close',
  'ticket.my_ticket': 'My Tickets',
  'ticket.new_ticket': 'New Ticket',
  'ticket.new_ticket_modal_title': 'New Ticket',
  'ticket.new_ticket_modal_confirm': 'Confirm',
  'ticket.new_ticket.modal_cancel': 'Cancel',
  'ticket.subject': 'Subject',
  'ticket.please_enter_subject': 'Please enter a subject',
  'ticket.level': 'Ticket Priority',
  'ticket.please_select_level': 'Please select the ticket priority',
  'ticket.message': 'Message',
  'ticket.please_enter_issue': 'Please describe the problem you encountered',
  // traffic
  'traffic.table_record_time': 'Record Time',
  'traffic.table_tx': 'Actual Upload',
  'traffic.table_rx': 'Actual Download',
  'traffic.table_rate': 'Deduction Rate',
  'traffic.table_total': 'Total',
  'traffic.table_total_tip': 'Formula: (Actual Upload + Actual Download) x Deduction Rate = Deduct Transfer Data',
  'traffic.traffic_detail': 'Transfer Data Details',
  'traffic.today': 'Today',
  'traffic.month': 'Month',
  'traffic.week': 'Week',
  // tutorial
  'tutorial.use_tutorial': 'Use Tutorial',
  // one_click_subscribe
  'one_click_subscribe.copy_success': 'Copied successfully',
  'one_click_subscribe.copy_subscribe_url': 'Copy subscription URL',
  'one_click_subscribe.import': 'Import to',
  'one_click_subscribe': 'Quick Subscription',
  'one_click_subscribe.copy_subscribe': 'Copy Subscription URL',
  // transfer_modal
  'transfer_modal.title': 'Transfer invitation commission to account balance',
  'transfer_modal.confirm': 'Confirm',
  'transfer_modal.cancel': 'Cancel',
  'transfer_modal.alert': 'The transferred balance will only be used for {title} payment',
  'transfer_modal.commission_balance': 'Current invitation balance',
  'transfer_modal.transfer_balance': 'transfer amount',
  'transfer_modal.please_enter_transfer_balance': 'Please enter the amount to be transferred to the balance',
  // chat
  'chat.please_enter_message': 'Please enter to reply to the ticket...',
  // withdraw_modal
  'withdraw_modal.title': 'Apply for withdrawal',
  'withdraw_modal.confirm': 'Confirm',
  'withdraw_modal.cancel': 'Cancel',
  'withdraw_modal.withdraw_method': 'Withdrawal Method',
  'withdraw_modal.please_select_method': 'Please select a withdrawal method',
  'withdraw_modal.withdraw_account': 'Withdrawal Account',
  'withdraw_modal.please_enter_account': 'Please enter the withdrawal account',
  'withdraw_modal.alipay': 'Alipay',
  'withdraw_modal.paypal': 'PayPal',
  'withdraw_modal.usdt': 'USDT',
  'withdraw_modal.btc': 'Bitcoin'
}
