export default {
  'request.error': 'Request failed',
  // cycle_text
  'cycle.month_price': '월별',
  'cycle.quarter_price': '분기별',
  'cycle.half_year_price': '반년',
  'cycle.year_price': '1년지불',
  'cycle.two_year_price': '2년지불',
  'cycle.three_year_price': '3년지불',
  'cycle.onetime_price': '1회지불',
  'cycle.reset_price': '데이터 재설정 패키지',
  // order_status
  'order_status.no_paid': '지불 보류 중',
  'order_status.opening': '활성 보류 중',
  'order_status.cancel': '취소됨',
  'order_status.done': '완료됨',
  'order_status.surplus': '변환됨',
  // commission_status
  'commission_status.pending_confirm': '승인중',
  'commission_status.confirm': '확인중',
  'commission_status.done': '완료됨',
  'commission_status.reject': '무효',
  // header
  'header.user_center': '사용자 센터',
  'header.logout': '로그아웃',
  'header.search': '검색',
  // nav
  'nav.dashboard': '대시보드',
  'nav.subscribe': '구독',
  'nav.my_subscribe': '나의 구독',
  'nav.buy_subscribe': '구독 구매',
  'nav.bill': '청구서',
  'nav.my_order': '나의 주문',
  'nav.my_invite': '내 초대장',
  'nav.user': 'Account',
  'nav.user_center': '사용자 센터',
  'nav.my_ticket': '나의 티켓',
  'nav.traffic_detail': '데이터 전송정보',
  'nav.knowledge': '기술자료',
  // dashboard
  'dashboard.not_bind_telegram': '아직 텔레그램에 연결되지 않음',
  'dashboard.click_here_bind': '텔레그램에 연결하려면 여기를 클릭하십시오.',
  'dashboard.announcement': '공지사항',
  'dashboard.override': '개요',
  'dashboard.pending_order': '보류중인 주문',
  'dashboard.pending_ticket': '보류중인 티켓',
  'dashboard.my_invite': '내 초대장',
  'dashboard.my_subscribe': '내 구독',
  'dashboard.add_subscribe': '구독 신청',
  'dashboard.not_expire': '구독은 시간 제한이 없습니다.',
  'dashboard.expired': '만료 됨',
  'dashboard.subscribe_info': '이용기간{date}까지, 만료기간까지 남은 {day}일,  {reset_day}일 후 데이터 재설정됩니다.',
  'dashboard.traffic_info': '사용됨{used} / 합계 {total}',
  'dashboard.view_subscribe': '구독보기',
  'dashboard.renew': '추가비용',
  // forgetPassword
  'forgetPassword.email': '이메일',
  'forgetPassword.email_verify_code': '이메일 확인코드',
  'forgetPassword.send': '발송',
  'forgetPassword.password': '비밀번호',
  'forgetPassword.reset_password': '비밀번호 재설정',
  'forgetPassword.back_login': '로그인돌아가기',
  // invite
  'invite.table_code': '초대코드',
  'invite.table_create_time': '생성일자',
  'invite.table_action': '동작',
  'invite.copy_link': '링크 복사',
  'invite.table_complete_time': '완료일자',
  'invite.table_commission_balance': '수수료',
  'invite.table_commission_status': '수수료 상태',
  'invite.override': '초대개요',
  'invite.register_count': '등록된 사용자수',
  'invite.commission_rate': '수수료율',
  'invite.confirm_commission': '승인대기 수수료',
  'invite.confirm_commission_tip': '승인을 마친 후 수수료 계좌로 입금됩니다.',
  'invite.invite_code_manage': '초대 코드 관리',
  'invite.generate_code': '초대코드생성',
  'invite.detail': '초대 세부 정보',
  'invite.copy_success': '클립보드에 복사되었습니다',
  // login
  'login.email': '이메일',
  'login.password': '비밀번호',
  'login': '로그인',
  'login.register': '회원가입',
  'login.forget_password': '비밀번호찾기',
  // order
  'order.table_no': '# 주문번호',
  'order.table_cycle': '유형 / 결제주기',
  'order.table_amount': '주문 금액',
  'order.table_status': '주문상태',
  'order.table_create_time': '주문날짜',
  'order.table_action': '동작',
  'order.view_detail': '상세보기',
  'order.cancel': '취소',
  'order.order_manage': '주문관리',
  'order.please_select_pay_method': '지급 방법을 선택하십시오.',
  'order.please_check_credit_card': '신용카드 결제 정보를 확인하십시오.',
  'order.order_detail': '주문 상세내역',
  'order.product': '제품',
  'order.type_cycle': '유형 / 결제주기',
  'order.amount': '금액',
  'order.traffic': '데이터 전송',
  'order.discount': '할인',
  'order.surplus': '공제액',
  'order.refund': '환급',
  'order.balance_pay': '잔액지급',
  'order.pay_method': '지불방식',
  'order.enter_credit_info': '신용카드 결제 정보 입력',
  'order.credit_alert': '고객님의 카드 정보는 결제에만 사용되며 서버에 저장되지 않습니다.',
  'order.total_amount': '합계 금액',
  'order.total': '합계',
  'order.checkout': '계산',
  'order.waiting_payment': 'お支払い待ち',
  'order.result_opening_title': '개통중',
  'order.result_opening_sub_title': '주문 처리 중입니다. 1-3분 정도 기다리십시오.',
  'order.result_cancel_title': '취소',
  'order.result_cancel_sub_title': '주문서 시간 초과 지불로 인해 이미 취소되었습니다.',
  'order.result_success_title': '완료',
  'order.result_success_sub_title': '주문서 결제 완료 및 개통.',
  // plan
  'plan.select_subscribe': '구독 선택',
  'plan.buy': '바로 구독하기',
  'plan.setting_subscribe': '구독 설정',
  'plan.discount': '할인',
  'plan.cycle': '지불주기',
  'plan.have_coupon': '쿠폰이 있나요?',
  'plan.coupon_verify': '인증',
  'plan.order_total_amount': '주문총액',
  'plan.place_order': '주문',
  'plan.total': '합계.',
  'plan.subscribe_change_title': '구독변경 주의사항',
  'plan.subscribe_change_content': '주의해 주십시오. 구독을 변경하면 현재 구독을 덮어쓰게 됩니다.',
  'plan.subscribe_not_renew': '이 구독을 갱신할 수 없습니다.',
  'plan.choose_another_subscribe': '다른 구독 선택',
  // profile
  'profile.user_center': '사용자 센터',
  'profile.my_wallet': '내 지갑',
  'profile.balance_tip': '잔액(서비스 구매만 가능)',
  'profile.commission_balance_tip': '초대수수료(출금 가능)',
  'profile.wallet_component': '지갑 세부 정보',
  'profile.transfer': '대체',
  'profile.commission_withdraw': '초대 수수료 인출',
  'profile.change_password': '비밀번호 변경',
  'profile.save': '변경저장',
  'profile.old_password': '이전 비밀번호',
  'profile.new_password': '새 비밀번호',
  'profile.re_new_password': '새 비밀번호확인',
  'profile.please_enter_old_password': '이전 암호를 입력하십시오.',
  'profile.please_enter_new_password': '새 암호를 입력하십시오.',
  'profile.please_enter_re_new_password': '새 암호를 다시 입력하십시오.',
  'profile.notice': '알림',
  'profile.expire_remind': '구독 만료 이메일 알림',
  'profile.traffic_remind': '전송 데이터 이메일 경고 부족',
  'profile.bind_telegram': '텔레그램 링크',
  'profile.start': '바로 시작',
  'profile.reset_subscribe': '구독정보 초기화',
  'profile.reset': '재설정',
  'profile.reset_info_notify_title': '구독을 재설정하시겠습니까?',
  'profile.reset_info_notify_content': '계정정보 또는 구독정보 노출의 경우 이 옵션을 사용하여 UUID를 재설정하고 재설정 후 구독이 변경되므로 다시 구독해야 합니다.',
  'profile.reset_info_notify_success': '변경완료',
  'profile.two_password_error': '입력한 두 개의 새 암호가 일치하지 않습니다.',
  // reg
  'register.two_password_error': '입력한 암호가 일치하지 않습니다.',
  'register.email': '이메일',
  'register.verify_code': '이메일 확인코드',
  'register.password': '비밀번호',
  'register.re_password': '비밀번호',
  'register.send': '발송',
  'register.invite_code_require': '초대코드',
  'register.invite_code': '초대 코드(선택 사항)',
  'register': '등록하다',
  'register.back_login': '로그인으로 돌아가기',
  'register.tos_url': '<a target="_blank" href="{url}">서비스 조항</a>를 읽고 동의합니다.',
  'register.please_agree_tos': '서비스 약관에 동의하십시오.',
  // subscribe
  'subscribe.table_name': '명칭',
  'subscribe.table_tag': '설명',
  'subscribe.table_action': '동작',
  'subscribe.table_status': '상태',
  'subscribe.table_status_tip': '최근 5분간의 온라인상태',
  'subscribe.table_rate': '환율',
  'subscribe.table_rate_tip': '통신량은 해당 환율에 따라 계산됩니다.',
  'subscribe.more_action': '더 많은 동작',
  'subscribe.copy_success': '성공적으로 복사됨',
  'subscribe.copy_link': '링크 복사',
  'subscribe.my_subscribe': '내 구독',
  'subscribe.add_subscribe': '구독 주문',
  'subscribe.not_expire': '구독 기간은 무제한입니다.',
  'subscribe.expired': '기한 만료',
  'subscribe.subscribe_info': '이용기한 {date}까지, 만료까지는 {day}일, {reset_day}일 후 데이터 재설정됩니다.',
  'subscribe.traffic_info': '사용됨{used} / 합계 {total}',
  'subscribe.renew': '추가비용',
  'subscribe.action': '동작',
  'subscribe.reset_traffic': '전송 데이터 재설정',
  'subscribe.reset_info': '구독 정보 초기화',
  'subscribe.node_status': '서버 상태',
  'subscribe.no_node': '이용 가능한 서버가 없습니다, 정기 구입 기간이 만료되거나 구입되지 않은 경우는',
  'subscribe.no_node_renew': '추가 비용',
  'subscribe.no_node_go': '구독',
  'subscribe.reset_traffic_notify_title': '당월 데이터 초기화하시겠습니까?',
  'subscribe.reset_traffic_notify_content': '"확인"을 클릭하면 결제 페이지로 이동합니다. 주문이 결제되면 시스템이 해당 달의 사용된 데이터를 삭제합니다.',
  'subscribe.reset_traffic_notify_confirm': '확인',
  'subscribe.reset_traffic_notify_cancel': '취소',
  'subscribe.reset_info_notify_title': '구독을 재설정하시겠습니까?',
  'subscribe.reset_info_notify_content': '계정 정보 또는 구독 정보 노출의 경우 이 옵션을 사용하여 UUID를 재설정하고 재설정 후 구독이 변경되므로 다시 구독해야 합니다.',
  'subscribe.reset_info_notify_success': '초기화 성공',
  // ticket
  'ticket.low': 'Low',
  'ticket.middle': 'Medium',
  'ticket.high': 'High',
  'ticket.table_subject': '제목',
  'ticket.table_level': '티켓 우선 순위',
  'ticket.table_status': '티켓 상태',
  'ticket.table_create_time': '생성 시간',
  'ticket.table_last_reply': '마지막 응답',
  'ticket.table_action': '조작',
  'ticket.status_closed': '종료',
  'ticket.status_pending': '응답 대기 중',
  'ticket.status_reply': '응답됨',
  'ticket.action_view': '열람',
  'ticket.action_close': '종료',
  'ticket.my_ticket': '나의 문의',
  'ticket.new_ticket': '신규문의',
  'ticket.new_ticket_modal_title': '신규문의',
  'ticket.new_ticket_modal_confirm': '확인',
  'ticket.new_ticket.modal_cancel': '취소',
  'ticket.subject': '제목',
  'ticket.please_enter_subject': '문의제목을 입력해주세요',
  'ticket.level': '우선 순위',
  'ticket.please_select_level': '원하시는 우선순위를 선택해주세요',
  'ticket.message': '내용',
  'ticket.please_enter_issue': 'Please describe the problem you encountered',
  // traffic
  'traffic.table_record_time': '기록 날짜',
  'traffic.table_tx': '업로드',
  'traffic.table_rx': '다운로드',
  'traffic.table_rate': '공제율',
  'traffic.table_total': '합계',
  'traffic.table_total_tip': '수식 : (실제 업로드 + 실제 다운로드) x 공제율 = 차감 전송 데이터',
  'traffic.traffic_detail': '전송 데이터 세부 정보',
  'traffic.today': '오늘',
  'traffic.month': '이번 달',
  'traffic.week': '이번 주',
  // one_click_subscribe
  'one_click_subscribe.copy_success': '복사 성공',
  'one_click_subscribe.copy_subscribe_url': '구독 URL 복사',
  'one_click_subscribe.import': '가져오기',
  'one_click_subscribe': '원클릭 구독',
  'one_click_subscribe.copy_subscribe': '구독 URL 복사',
  // transfer_modal
  'transfer_modal.title': '계정 잔액으로 초대수수료 이전',
  'transfer_modal.confirm': '확인',
  'transfer_modal.cancel': '취소',
  'transfer_modal.alert': '이체된 잔액은 {title}에서만 이용가능합니다.',
  'transfer_modal.commission_balance': '현재 초대잔액',
  'transfer_modal.transfer_balance': '대체금액',
  'transfer_modal.please_enter_transfer_balance': '잔액으로 이전할 금액을 입력하십시오.',
  // chat
  'chat.please_enter_message': '문의사항 입력해주세요...',
  // withdraw_modal
  'withdraw_modal.title': '출금 신청',
  'withdraw_modal.confirm': '확인',
  'withdraw_modal.cancel': '취소',
  'withdraw_modal.withdraw_method': '출금 방법',
  'withdraw_modal.please_select_method': '출금 방법을 선택하십시오.',
  'withdraw_modal.withdraw_account': '입금 계좌',
  'withdraw_modal.please_enter_account': '수취인 계좌를 입력해 주세요',
  // bind_telegram
  'bind_telegram_modal.confirm': '알겠습니다.',
  'bind_telegram_modal.title': '텔레그램연동',
  'bind_telegram_modal.step_1': '첫번째',
  'bind_telegram_modal.step_2': '두번째',
  'bind_telegram_modal.open_telegram_search': 'Telegram 검색 열기 ',
  'bind_telegram_modal.send_bot_message': 'Telegram Bot으로 아래 내용을 전송',
  // knowledge
  'knowledge': '기술자료(사용방법)',
  'knowledge.last_release_date': '마지막 업데이트: {date}',
  'knowledge.copy_success' : '복사 성공'
  // new language
  'Dashboard': '대시보드',
  'My subscription': '내 구독',
  'To do event': 'To do event',
  'There are still unpaid orders': '아직 지불하지 않은 주문이 있습니다',
  'Pay now': '즉시 지불',
  'Ticket is being processed': '지금 처리중입니다.',
  'View now': '바로 보기',
  'Buy subscription': '구독 구매',
  'Knowledge': '기술자료',
  'My order': '나의 주문',
  'Personal Center': '개인 센터',
  'Flow details': '트래픽 내역',
  'Configure subscription': '구독 설정',
  'My invitation': '나의 초대',
  'Node status': '서버노드 상태',
  'There was no incident': '아무 일도 없었다.'
}
