export default {
  'request.error': 'Yêu cầu thất bại',
  // cycle_text
  'cycle.month_price': 'Một tháng',
  'cycle.quarter_price': 'Ba tháng',
  'cycle.half_year_price': 'Nửa Năm',
  'cycle.year_price': 'Một năm',
  'cycle.two_year_price': 'Hai Năm',
  'cycle.three_year_price': 'Ba Năm',
  'cycle.onetime_price': 'Vĩnh Viễn',
  'cycle.reset_price': 'Cập nhật dung lượng',
  // order_status
  'order_status.no_paid': 'Đợi thánh toán',
  'order_status.opening': 'Chờ đợi',
  'order_status.cancel': 'Đã Hủy',
  'order_status.done': 'Thực hiện',
  'order_status.surplus': 'Quy đổi',
  // commission_status
  'commission_status.pending_confirm': 'Được xác nhận',
  'commission_status.confirm': 'Đã xác nhận',
  'commission_status.done': 'Hoàn thành',
  'commission_status.reject': 'Bị từ chối',
  // header
  'header.user_center': 'Thông tin người dùng',
  'header.logout': 'Đăng Xuất',
  'header.search': 'Tìm Kiếm',
  // nav
  'nav.dashboard': 'Trang Chủ',
  'nav.subscribe': 'Gói dịch vụ',
  'nav.my_subscribe': 'Gói dịch vụ của tôi',
  'nav.buy_subscribe': 'Mua Gói Dịch Vụ',
  'nav.bill': 'Tài Chính',
  'nav.my_order': 'Đơn Hàng Của Tôi',
  'nav.my_invite': 'Lời mời của tôi',
  'nav.user': 'Người Dùng',
  'nav.user_center': 'Thông tin người dùng',
  'nav.my_ticket': 'Hỗ Trợ',
  'nav.traffic_detail': 'Dung lượng đã sử dụng',
  'nav.knowledge': 'Học Hỏi & Hướng Dẫn',
  // dashboard
  'dashboard.not_bind_telegram': 'Chưa liên kếtTelegram',
  'dashboard.click_here_bind': 'Nhấp vào đây để liên kết',
  'dashboard.announcement': 'Thông báo',
  'dashboard.override': 'Tổng quát',
  'dashboard.pending_order': 'Đang đợi thanh toán',
  'dashboard.pending_ticket': 'Chờ trả lời',
  'dashboard.my_invite': 'Lời mời của tôi',
  'dashboard.my_subscribe': 'Gói dịch vụ của tôi',
  'dashboard.add_subscribe': 'Mua gói dịch vụ',
  'dashboard.not_expire': 'Gói dịch vụ có giá trị trong thời gian dài',
  'dashboard.expired': 'Tài khoản hết hạn',
  'dashboard.subscribe_info': 'Năm {date} đến hạn，Thời gian đến hạn còn {day} ngày.',
  'dashboard.traffic_info': 'Đã sử dụng {used} / Tổng dung lượng {total}',
  'dashboard.view_subscribe': 'Xem gói dịch vụ',
  'dashboard.renew': 'Gia hạn',
  // forgetPassword
  'forgetPassword.email': 'Email',
  'forgetPassword.email_verify_code': 'Mã xác minh Email',
  'forgetPassword.send': 'Gửi mã',
  'forgetPassword.password': 'Mật khẩu',
  'forgetPassword.reset_password': 'Đặt lại mật khẩu',
  'forgetPassword.back_login': 'Quay lại trang đăng nhập',
  // invite
  'invite.table_code': 'Mã giới thiệu',
  'invite.table_create_time': 'Thời gian thực hiện',
  'invite.table_action': 'Thao tác',
  'invite.copy_link': 'Sao chép liên kết',
  'invite.table_complete_time': 'Thời gian hoàn thành',
  'invite.table_commission_balance': 'Tiền Hoa hồng',
  'invite.table_commission_status': 'Trạng thái tiền hoa hồng',
  'invite.override': 'Bảng chi tiết người được mời',
  'invite.register_count': 'Số lượng người dùng đã đăng ký',
  'invite.commission_rate': 'Phần trăm hoa hồng được hưởng',
  'invite.confirm_commission': 'Tiền hoa hồng đang được xác nhận',
  'invite.confirm_commission_tip': 'Tiền hoa hồng sau khi được xác nhận sẽ được gửi vào tài khoản tiền hoa hồng của bạn.',
  'invite.invite_code_manage': 'Quản lý mã giới thiệu',
  'invite.generate_code': 'Tạo mã giới thiệu',
  'invite.detail': 'Chi tiết',
  'invite.copy_success': 'Sao chép thành công',
  // login
  'login.email': 'Email',
  'login.password': 'Mật khẩu',
  'login': 'Đăng nhập',
  'login.register': 'Đăng kí',
  'login.forget_password': 'Quên mật khẩu',
  // order
  'order.table_no': '# Mã đơn hàng',
  'order.table_cycle': 'Chu kì',
  'order.table_amount': 'Tổng tiền đơn hàng',
  'order.table_status': 'Trạng thái đơn hàng',
  'order.table_create_time': 'Thời gian tạo',
  'order.table_action': 'Thao tác',
  'order.view_detail': 'Xem chi tiết',
  'order.cancel': 'Hủy',
  'order.order_manage': 'Quản lí đơn hàng',
  'order.please_select_pay_method': 'Chọn hình thức thanh toán',
  'order.please_check_credit_card': 'Vui lòng kiểm tra thông tin thanh toán thẻ',
  'order.order_detail': 'Chi tiết đơn hàng',
  'order.product': 'Sản phẩm',
  'order.type_cycle': 'Loại hình/Chu kì',
  'order.amount': 'Tổng cộng',
  'order.traffic': 'Dung lượng',
  'order.discount': 'Chiết Khấu',
  'order.surplus': 'Quy đổi',
  'order.refund': 'Hoàn tiền',
  'order.balance_pay': 'Thanh toán qua số dư tài khoản',
  'order.pay_method': 'Phương thức thanh toán',
  'order.enter_credit_info': 'Điền thông tin thanh toán thẻ tín dụng',
  'order.credit_alert': 'Thông tin thẻ tín dụng của bạn sẽ chỉ sử dụng cho khoản khấu trừ hiện tại, hệ thống sẽ không lưu thông tin đó, đây là cách an toàn nhất',
  'order.total_amount': 'Tổng cộng',
  'order.total': 'Tổng cộng',
  'order.checkout': 'Thanh toán',
  'order.waiting_payment': 'Đợi Thanh toán',
  'order.result_opening_title': 'Đang khởi tạo',
  'order.result_opening_sub_title': 'Hệ thống đang xử lý, vui lòng đợi 1-3 phút.',
  'order.result_cancel_title': 'Đã hủy',
  'order.result_cancel_sub_title': 'Đơn hàng đã bị hủy do hết thời gian thanh toán.',
  'order.result_success_title': 'Thành công',
  'order.result_success_sub_title': 'Đơn hàng đã thanh toán thành công.',

  // plan
  'plan.select_subscribe': 'Chọn gói dịch vụ',
  'plan.buy': 'Mua ngay',
  'plan.setting_subscribe': 'Cài đặt',
  'plan.discount': 'Chiết khấu',
  'plan.cycle': 'Chu kì thanh toán ',
  'plan.have_coupon': 'Có phiếu giảm giá',
  'plan.coupon_verify': 'Xác ninh',
  'plan.order_total_amount': 'Tổng cộng',
  'plan.place_order': 'Mua ngay',
  'plan.total': 'Tổng cộng',
  'plan.subscribe_change_title': 'Thông báo về khi mua gói dịch vụ mới',
  'plan.subscribe_change_content': 'Việc mua gói dịch vụ mới sẽ làm thay đổi gói dịch vụ hiện tại, xin lưu ý',
  'plan.subscribe_not_renew': 'Không thể thay đổi bản đăng ký',
  'plan.choose_another_subscribe': 'Chọn một sản phẩm khác',
  // profile
  'profile.user_center': 'Trung tâm kiểm soát',
  'profile.my_wallet': 'Ví tiền của tôi',
  'profile.balance_tip': 'Số dư tài khoản',
  'profile.commission_balance_tip': 'Tiền hoa hồng (có thể rút)',
  'profile.wallet_component': 'Chi tiết ví tiền',
  'profile.transfer': 'Chuyển đổi',
  'profile.commission_withdraw': 'Rút tiền hoa hồng',
  'profile.change_password': 'Đổi mật khẩu',
  'profile.save': 'Lưu',
  'profile.old_password': 'Mật khẩu hiện tại',
  'profile.new_password': 'Mật khẩu mới',
  'profile.re_new_password': 'Vui lòng nhập lại mật khẩu mới',
  'profile.please_enter_old_password': 'Vui lòng nhập mật khẩu hiện tại',
  'profile.please_enter_new_password': 'Vui lòng nhập mật khẩu mới',
  'profile.please_enter_re_new_password': 'Vui lòng nhập lại mật khẩu mới',
  'profile.notice': 'Thông báo',
  'profile.expire_remind': 'Bật email nhắc nhở hết hạn',
  'profile.traffic_remind': 'Email nhắc nhở dung lượng',
  'profile.bind_telegram': 'Liên kết Telegram',
  'profile.start': 'Bắt đầu ngay',
  'profile.reset_subscribe': 'Reset gói dịch vụ',
  'profile.reset': 'Làm mới',
  'profile.reset_info_notify_title': 'Bạn có chắc chắn muốn đặt lại liên kết không?',
  'profile.reset_info_notify_content': 'Nếu địa chỉ đăng ký hoặc thông tin của bạn bị rò rỉ có thể thao tác ở đây.Sau khi đặt lại UUID và liên kết của bạn sẽ  được thay đổi , bạn cần thêm lại liên kết mới.',
  'profile.reset_info_notify_success': 'Làm mới thành công',
  'profile.two_password_error': '2 lần đăng nhập mật khẩu mới không đúng',
  // reg
  'register.two_password_error': '2 lần đăng nhập mật khẩu không đúng',
  'register.email': 'Email',
  'register.verify_code': 'Mã xác minh Email',
  'register.password': 'Mật khẩu',
  'register.re_password': 'Nhập lại mật khẩu',
  'register.send': 'Gửi mã',
  'register.invite_code_require': 'Mã giới thiệu',
  'register.invite_code': 'Nhập mã giới thiệu (nếu có)',
  'register': 'Đăng kí',
  'register.back_login': 'Quay lại đăng nhập',
  'register.tos_url': 'Tôi đã đọc và đồng ý <a target="_blank" href="{url}">điều khoản dịch vụ</a>',
  'register.please_agree_tos': 'Hãy đồng ý với điều khoản',
  // subscribe
  'subscribe.table_name': 'Tên',
  'subscribe.table_tag': 'Kí hiệu',
  'subscribe.table_action': 'Thao tác',
  'subscribe.table_status': 'Trạng thái',
  'subscribe.table_status_tip': 'Người dùng trực tuyến trong 5 phút',
  'subscribe.table_rate': 'Bội suất',
  'subscribe.table_rate_tip': 'Lưu lượng sử dụng sẽ được nhân với bội suất',
  'subscribe.more_action': 'Nhiều hơn',
  'subscribe.copy_success': 'Sao chép thành công',
  'subscribe.copy_link': 'Sao chép liên kết',
  'subscribe.my_subscribe': 'Gói dịch vụ của tôi',
  'subscribe.add_subscribe': 'Mua gói dịch vụ',
  'subscribe.not_expire': 'Gói dịch vụ có giá trị trong thời gian dài',
  'subscribe.expired': 'Tài khoản hết hạn',
  'subscribe.subscribe_info': 'Năm {date} đến hạn，Thời gian đến hạn còn {day} ngày',
  'subscribe.traffic_info': 'Đã sử dụng {used} / Tổng dung lượng {total}',
  'subscribe.renew': 'Gia hạn',
  'subscribe.action': 'Thao tác',
  'subscribe.reset_traffic': 'Mua thêm dung lượng',
  'subscribe.reset_info': 'Thay đổi liên kết',
  'subscribe.node_status': 'Trạng thái của máy chủ',
  'subscribe.no_node': 'Không có máy chủ, nếu bạn chưa mua gói dịch vụ hoặc gói dịch vụ đã hết hạn, vui lòng',
  'subscribe.no_node_renew': 'Gia hạn',
  'subscribe.no_node_go': 'Mua gói dịch vụ',
  'subscribe.reset_traffic_notify_title': 'Bạn có chắc  muốn làm mới lại dung lượng trong tháng ?',
  'subscribe.reset_traffic_notify_content': 'Ấn [Xác nhận] để chuyển sang trang thanh toán, sau khi thanh toán dung lượng tháng của bạn sẽ trở về số 0 và cộng thêm dung lượng vừa mua.',
  'subscribe.reset_traffic_notify_confirm': 'Xác nhận',
  'subscribe.reset_traffic_notify_cancel': 'Hủy',
  'subscribe.reset_info_notify_title': 'Bạn có chắc chắn muốn đặt lại liên kết không?',
  'subscribe.reset_info_notify_content': 'Nếu liên kết và thông tin của bạn bị lộ ra ngoài có thể làm thao tác này. Sau khi làm mới UUID và liên kết của bạn sẽ được thay đổi. Bạn cần bắt đầu thêm lại liên kết vào phần mềm. ',
  'subscribe.reset_info_notify_success': 'Làm mới thành công',
  // ticket
  'ticket.low': 'Thấp',
  'ticket.middle': 'Trung bình',
  'ticket.high': 'Cao',
  'ticket.table_subject': 'Chủ đề',
  'ticket.table_level': 'Mức độ',
  'ticket.table_status': 'Trạng thái',
  'ticket.table_create_time': 'Tạo thời gian',
  'ticket.table_last_reply': 'Lần trả lời cuối',
  'ticket.table_action': 'Thao tác',
  'ticket.status_closed': 'Đã đóng',
  'ticket.status_pending': 'Đợi trả lời',
  'ticket.status_reply': 'Đã trả lời',
  'ticket.action_view': 'Xem',
  'ticket.action_close': 'Đóng',
  'ticket.my_ticket': 'Liên hệ với chúng tôi',
  'ticket.new_ticket': 'Tạo hỗ trợ',
  'ticket.new_ticket_modal_title': 'Tin nhắn mới',
  'ticket.new_ticket_modal_confirm': 'Xác nhận',
  'ticket.new_ticket.modal_cancel': 'Hủy',
  'ticket.subject': 'Chủ đề',
  'ticket.please_enter_subject': 'Vui lòng nhập tiêu đề tin nhắn',
  'ticket.level': 'Mức độ',
  'ticket.please_select_level': 'Vui lòng chọn cấp độ tin nhắn',
  'ticket.message': 'Nội dung tin nhắn',
  'ticket.please_enter_issue': 'Mô tả vấn đề bạn gặp phải',
  // traffic
  'traffic.table_record_time': 'Ghi nhớ thời gian',
  'traffic.table_tx': 'Thực tế tải lên',
  'traffic.table_rx': 'Thực tế tải xuống',
  'traffic.table_rate': 'Bội suất',
  'traffic.table_total': 'Tổng dung lượng',
  'traffic.table_total_tip': 'Công thức : ( Thực tế tải lên + Thực tế tải xuống ) x  Bội suất = Dung lượng đã sử dụng',
  'traffic.traffic_detail': 'Chi tiết dung lượng',
  'traffic.today': 'Hôm nay',
  'traffic.month': 'Tháng nay',
  'traffic.week': 'Tuần này',
  // one_click_subscribe
  'one_click_subscribe.copy_success': 'Sao chép thành công',
  'one_click_subscribe.copy_subscribe_url': 'Sao chép liên kết',
  'one_click_subscribe.import': 'Chuyển đến',
  'one_click_subscribe': 'Nhấp chuột để đồng bộ máy chủ',
  'one_click_subscribe.copy_subscribe': 'Nhấp chuột để đồng bộ máy chủ',
  // transfer_modal
  'transfer_modal.title': 'Tiền hoa hồng chuyển sang tài khoản của bạn',
  'transfer_modal.confirm': 'Xác nhận',
  'transfer_modal.cancel': 'Hủy',
  'transfer_modal.alert': 'Sau khi chuyển đổi sang tài khoản, tiền này chỉ dùng để mua {title} gói dịch vụ của chúng tôi',
  'transfer_modal.commission_balance': 'Số dư tài khoản hoa hồng',
  'transfer_modal.transfer_balance': 'Số tiền muốn đổi',
  'transfer_modal.please_enter_transfer_balance': 'Vui lòng nhập số tiền bạn muốn đổi sang tài khoản',
  // chat
  'chat.please_enter_message': 'Điền thông tin  nội dung trả lời...',
  // withdraw_modal
  'withdraw_modal.title': 'Đăng kí rút tiền',
  'withdraw_modal.confirm': 'Xác nhận',
  'withdraw_modal.cancel': 'Hủy',
  'withdraw_modal.withdraw_method': 'Phương thức rút tiền',
  'withdraw_modal.please_select_method': 'Chọn hình thức rút tiền ',
  'withdraw_modal.withdraw_account': 'Tài khoản rút tiền',
  'withdraw_modal.please_enter_account': 'Vui lòng điền tài khoản rút  tiền',
  // bind_telegram
  'bind_telegram_modal.confirm': 'Tôi biết',
  'bind_telegram_modal.title': 'Thêm Telegram',
  'bind_telegram_modal.step_1': 'Bước đầu tiên',
  'bind_telegram_modal.step_2': 'Bước thứ hai',
  'bind_telegram_modal.open_telegram_search': 'Bật Telegram tìm kiếm',
  'bind_telegram_modal.send_bot_message': 'Gửi cho bot',
  // knowledge
  'knowledge': 'Học hỏi & Hướng dẫn',
  'knowledge.last_release_date': 'Lần cập nhật cuối cùng vào: {date}',
  'knowledge.copy_success' : 'Sao chép thành công',
  // new language
  'Dashboard': 'Trang chủ',
  'My subscription': 'Gói dịch vụ của tôi',
  'To do event': 'Để thực hiện',
  'There are still unpaid orders': 'Vẫn còn những đơn hàng chưa thanh toán',
  'Pay now': 'Thanh toán ngay',
  'Ticket is being processed': 'Đang xử lý lệnh làm việc.',
  'View now': 'Xem ngay',
  'Buy subscription': 'Mua gói dịch vụ',
  'Knowledge': 'Học hỏi & hướng dẫn',
  'My order': 'Đơn hàng của tôi',
  'Personal Center': 'Trung tâm cá nhân',
  'Flow details': 'Chiết tiết hoa hồng',
  'Configure subscription': 'Định cấu hình đăng ký',
  'My invitation': 'Mã giới thiệu của tôi',
  'Node status': 'Không biết',
  'There was no incident': 'Không có chuyện gì cả.',
  'Copied': 'Copy',
  'Product information': 'Thông tin sản phẩm',
  'Product name': 'Tên sản phẩm',
  'Type/Period': 'Loại / Kỳ',
  'Product flow': 'Dòng sản phẩm',
  'Order information': 'Thông tin đặt hàng',
  'Close order': 'Đóng đơn hàng',
  'Order number': 'Số đơn hàng',
  'Discount amount': 'Số tiền chiết khấu',
  'Deduction amount': 'Số tiền khấu trừ',
  'Refund amount': 'Số tiền hoàn trả',
  'Balance payment': 'Bản cân đối chi thu',
  'Creation time': 'Thời gian sáng tạo',
  'My tickets': 'Đơn hỗ trợ của tôi',
  'Tickets history': 'Lịch sử đơn hỗ trợ',
  'Reset flow after {reset_day} day': 'Sau ngày {reset_day} dung lượng sẽ được làm mới.'
  'Node name': 'Tên máy chủ',
  'Due on {date}, {day} days before expiration': 'Năm {date} đến hạn，Thời gian đến hạn còn {day} ngày.'
}
